### PR TITLE
Feature/indent char

### PR DESCRIPTION
**Pull request by stephenlautier**
Added indent char to be configurable (to use tabs).

Updated documentation since it was pointing to wrong config section

### CODE REVIEW

**Comment by BenDTU** [comment]
Nice work - I've been hoping for this feature.

**Comment by stephenlautier** [comment]
welcome :). @dweber019 can you look this please, as its a very small nice change. thanks!

**Comment by dweber019** [comment]
@stephenlautier thanks for the constitution will do a release today.

**Comment by stephenlautier** [comment]
@dweber019 cheers!

**Pull request merged**
